services:
  app:
    build: .
    image: learnmistschool
    container_name: learnmistschool_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend/learnmistschool.db:/app/learnmistschool.db
